INSERT INTO STATIONS(name,location) VALUES('Colonia Jardín (correspondencia con la líneas 10 y con Metro Ligero 3)',ST_GeomFromText('POINT()', 4326));
INSERT INTO STATIONS(name,location) VALUES('Prado de la Vega'                                                      ,ST_GeomFromText('POINT()', 4326));
INSERT INTO STATIONS(name,location) VALUES('Colonia de los Ángeles'                                                ,ST_GeomFromText('POINT()', 4326));
INSERT INTO STATIONS(name,location) VALUES('Prado del Rey'                                                         ,ST_GeomFromText('POINT()', 4326));
INSERT INTO STATIONS(name,location) VALUES('Somosaguas Sur'                                                        ,ST_GeomFromText('POINT()', 4326));
INSERT INTO STATIONS(name,location) VALUES('Somosaguas Centro'                                                     ,ST_GeomFromText('POINT()', 4326));
INSERT INTO STATIONS(name,location) VALUES('Pozuelo Oeste'                                                         ,ST_GeomFromText('POINT()', 4326));
INSERT INTO STATIONS(name,location) VALUES('Bélgica'                                                               ,ST_GeomFromText('POINT()', 4326));
INSERT INTO STATIONS(name,location) VALUES('Dos Castillas'                                                         ,ST_GeomFromText('POINT()', 4326));
INSERT INTO STATIONS(name,location) VALUES('Campus de Somosaguas'                                                  ,ST_GeomFromText('POINT()', 4326));
INSERT INTO STATIONS(name,location) VALUES('Avenida de Europa'                                                     ,ST_GeomFromText('POINT()', 4326));
INSERT INTO STATIONS(name,location) VALUES('Berna'                                                                 ,ST_GeomFromText('POINT()', 4326));
INSERT INTO STATIONS(name,location) VALUES('Estación de Aravaca.'                                                  ,ST_GeomFromText('POINT()', 4326));
