--INSERT INTO STATIONS(name,location,created_at,updated_at) VALUES('Nuevos Ministerios (correspondencia con líneas 6 y 10 y con Cercanías de Renfe)',ST_GeomFromText('POINT(-3.692354 40.446408)',4326),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); 
INSERT INTO STATIONS(name,location,created_at,updated_at) VALUES('Colombia (correspondencia con línea 9)'                                         ,ST_GeomFromText('POINT(-3.676860 40.456336)',4326),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); 
INSERT INTO STATIONS(name,location,created_at,updated_at) VALUES('Pinar del Rey'                                                                  ,ST_GeomFromText('POINT(-3.648911 40.468147)',4326),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); 
--INSERT INTO STATIONS(name,location,created_at,updated_at) VALUES('Mar de Cristal (correspondencia con la línea 4)'                                ,ST_GeomFromText('POINT(-3.638332 40.469421)',4326),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); 
INSERT INTO STATIONS(name,location,created_at,updated_at) VALUES('Campo de las Naciones'                                                          ,ST_GeomFromText('POINT(-3.616193 40.463899)',4326),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); 
INSERT INTO STATIONS(name,location,created_at,updated_at) VALUES('Aeropuerto T1-T2-T3'                                                            ,ST_GeomFromText('POINT(-3.568890 40.468596)',4326),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); 
INSERT INTO STATIONS(name,location,created_at,updated_at) VALUES('Barajas'                                                                        ,ST_GeomFromText('POINT(-3.582494 40.475746)',4326),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); 
INSERT INTO STATIONS(name,location,created_at,updated_at) VALUES('Aeropuerto T4.'                                                                 ,ST_GeomFromText('POINT(-3.594639 40.491218)',4326),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); 

