-- Linea 1
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,3  ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,4  ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,5  ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,6  ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,7  ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,8  ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,9  ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,10 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,11 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,12 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,13 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,14 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,15 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,16 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,17 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,18 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,19 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,20 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,21 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,22 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,23 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,24 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,25 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,26 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,27 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,28 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,29 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,30 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,31 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,32 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,33 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,34 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(33,137,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


-- Linea 2
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,11,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,17,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,35,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,36,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,37,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,38,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,39,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,43,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,44,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,45,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,46,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,48,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,49,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,50,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,51,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,52,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,53,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(34,69,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

-- Linea 3
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,17 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,50 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,55 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,56 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,57 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,58 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,59 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,60 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,61 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,62 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,63 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,64 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,65 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,66 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,68 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,69 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,70 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,71 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,72 ,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(35,116,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

-- Linea 4
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36, 3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,14,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,42,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,51,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,71,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,76,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,77,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,78,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,79,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,81,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,82,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,83,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,84,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,85,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,86,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,87,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,88,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,89,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,90,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,91,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,92,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,93,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(36,94,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

-- Linea 5
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37, 16,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37, 40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37, 48,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37, 65,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37, 68,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37, 76,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37, 82,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37, 96,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37, 97,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37, 98,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37, 99,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,100,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,101,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,102,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,103,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,104,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,107,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,108,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,110,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,114,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,115,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,116,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,117,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,118,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,119,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,120,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,121,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,122,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,123,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,124,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,125,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,126,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(37,127,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);



-- Linea 6
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38, 11,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38, 41,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38, 62,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38, 71,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38, 72,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38, 82,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38, 83,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,120,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,128,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,129,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,131,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,132,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,133,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,135,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,136,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,137,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,138,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,139,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,140,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,144,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,145,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,147,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,148,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,149,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,152,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,153,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,154,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(38,155,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


-- Linea 7
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39, 53,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39, 83,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,102,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); 
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,147,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); 
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,281,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,282,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,283,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,284,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,285,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,286,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,287,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,288,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,289,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,290,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,156,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,157,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,158,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,160,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,161,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,162,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,164,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,165,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,167,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,169,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,170,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,171,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,172,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,173,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,174,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(39,175,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

-- Linea 8
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40, 90,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,145,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,177,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,178,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,180,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,181,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,182,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,183,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

-- Linea 9
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,  6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41, 43,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41, 83,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,107,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); 
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,139,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP); 
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,177,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,184,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,185,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,186,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,187,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,189,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,190,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,192,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,193,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,197,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,199,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,200,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,201,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,202,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,203,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,204,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,205,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,206,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,207,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,208,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,209,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,210,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(41,211,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


-- Linea 10
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,  5,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,  6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42, 15,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42, 50,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42, 69,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42, 76,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,127,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,145,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,152,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,164,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,212,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,213,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,214,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,215,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,216,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,217,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,218,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,219,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,220,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,221,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,222,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,223,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,224,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,227,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,228,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,235,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,236,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,238,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,239,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,241,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(42,242,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);


-- Linea 11
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,132,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,244,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,245,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,246,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,247,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,248,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,249,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

-- Linea 12
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,242,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,251,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,252,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,253,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,254,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,255,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,256,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,257,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,258,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,259,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,260,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,261,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,262,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,263,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,264,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,265,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,266,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,267,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,268,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,269,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,270,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,271,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,272,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,273,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,274,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,275,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,276,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(44,277,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);



