INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,132,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,244,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,245,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,246,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,247,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,248,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(43,249,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
