INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40, 90,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,145,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,177,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,178,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,180,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,181,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,182,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO LINES_STATIONS (line_id,station_id,created_at,updated_at) VALUES(40,183,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
